### ISSUE TITLE
Errors compiling on Windows, Python 3.8, and USBTMC

### ISSUE THREAD

**Issue by Aaron-Purchase** [Hyperfine/pyTHM1176#8]
Hello Cedric,

I am setting this up for a THM1176 + CNC mapper but two errors appear (using Windows 10 + USBTMC).
1) Warning errors due to use of "is" instead of "==": C:\Users\apurc\Desktop\pyTHM1176-master\pyTHM1176\log_thm.py:37: SyntaxWarning: "is" with a literal. Did you mean "=="?
2) inability to locate probe: Traceback (most recent call last):
  File "C:\Users\apurc\Desktop\pyTHM1176-master\pyTHM1176\log_thm.py", line 67, in <module>
    thm = thm_api.Thm1176(backend.list_devices()[0], **params)  # You may want to ahve a smarter way of fetching the resource name
  File "C:\Users\apurc\Desktop\pyTHM1176-master\pyTHM1176\api\thm_usbtmc_api.py", line 174, in __init__
    self.setup(**kwargs)

What are the details to correct issue #2?

I really appreciate your help here.

Kind regards,
Aaron

**Comment by cedh4c** [comment]
The only way I can reproduce 2 in Windows is when the usb driver has not been switched to libsusb for the THM1176 using Zadig. I could see this happening also when more than one usbtmc device is connected and the THM is not the first device on the list. 
Aaron seems to have resolved the issue under Linux by changing the udev rules (notably permission should be 666).

The first issue ("is" vs "==") will be fixed in next PR. This is just sloppy syntax on my part which was allowed in older versions of Python and triggers a Warning in 3.8+.

**Comment by thazdaniel** [comment]
Hey cedh4c,

I am having the same problems as Aaron-Purchase, I am using libusb on windows and THM is the only device. I am using python 3.9 so the first issue I understand. but the second one is the big problem for me. I am doing something similar to Aaron-Purchase where I want to set up a THM1176 + CNC mapper. At the moment I am just trying to run the log_thm.py just to make sure things are working.

Thanks,

thaz

**Comment by cedh4c** [comment]
Hi @thazdaniel,
I'm not going to be able to look at this with hardware connected for a few days. Just to start troubleshooting, can you run in an ipython console or jupyter notebook run something along the lines of:
```
import usbtmc
print(usbtmc.list_devices())
```

And paste the output here? If you ahve the same error as Aaron, it's probably an empty list but it's worth double checking.

If that returns an empty list or None, my first guess is a driver issue. Which version of Zadig did you use? You did make sure to select the THM1176 in Zadig and then assign the libusb driver to it? Just double checking because that's the most likely problem.

I'll try to take a look with hardware connected in a couple days.
